project:
  type: website
  output-dir: docs

website:
  title: "Pokemon Battle Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: team-builder.qmd
        text: Team Builder
      - href: pokemon-battle.qmd
        text: Battle

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



